<a href="https://colab.research.google.com/github/pedroromerogonzalez-collab/CDD/blob/main/Ejemplo_2_con_LANDER_RODRIGO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Ejercicios con Pandas y Numpy en Google Colab

| **Estudiante** | _(escribe tu nombre aquí)_ |

**Objetivo:** abrir un archivo CSV, observar sus datos.

Usaremos `productos_ventas.csv`, separado por punto y coma (`;`).

## 1. Abrir el archivo con Pandas
Antes, debemos subir el archivo a Google Colab (a la izquierda clic en la carpeta **Archivos** y elegir el icono de flecha que es para **Subir al almacenamiento de sesión.**

`pd.read_csv()` lee el CSV. El parámetro `sep=';'` indica el separador de columnas.

In [ ]:
import pandas as pd


df = pd.read_csv('productos_ventas.csv', sep=';')
display(df.head(10))  #muestra primeros 20 registros
df.tail(2)  #muestra últimos 2 registros

,codigo,producto,categoria,ciudad,precio,stock,unidades_vendidas,anio,descuento_porcentaje
0,1001,Notebook,Computación,Concepción,689700,5,73,2024,3.20
1,1002,Mouse,Accesorios,Talcahuano,11100,15,142,2024,4.01
2,1003,Impresora,Oficina,Coronel,99300,6,10,2024,11.37
3,1004,Silla escritorio,Muebles,Chillán,78400,66,157,2024,4.48
4,1005,Monitor,Computación,San Pedro de la Paz,186300,85,142,2025,22.73
5,1006,Teclado,Accesorios,Los Ángeles,23100,77,74,2024,2.88
6,1007,Proyector,Oficina,Los Ángeles,352100,22,111,2025,14.33
7,1008,Escritorio,Muebles,Tomé,141300,29,89,2024,9.64
8,1009,Tablet,Computación,Chillán,193700,14,94,2025,21.60
9,1010,Pendrive,Accesorios,San Pedro de la Paz,9400,7,120,2026,5.67

,codigo,producto,categoria,ciudad,precio,stock,unidades_vendidas,anio,descuento_porcentaje
148,1149,Memoria RAM,Computación,Coronel,47500,55,140,2026,13.64
149,1150,Micrófono,Accesorios,Chillán,49200,79,59,2025,6.68

## 2. Saber cuántas filas y columnas tiene

In [ ]:
print('Filas y columnas:', df.shape)
print('Filas:', len(df))
print('Filas:', df.shape[0])
print('Columnas:', df.shape[1])

Filas y columnas: (150, 9)
Filas: 150
Filas: 150
Columnas: 9

## 3. Mostrar los nombres de las columnas

In [ ]:
print(df.columns.tolist())

['codigo', 'producto', 'categoria', 'ciudad', 'precio', 'stock', 'unidades_vendidas', 'anio', 'descuento_porcentaje']

## 4 Saber los tipos de datos de cada columna

In [ ]:
print(df.dtypes)

codigo                   int64
producto                object
categoria               object
ciudad                  object
precio                   int64
stock                    int64
unidades_vendidas        int64
anio                     int64
descuento_porcentaje    object
dtype: object

## 5. Consultar una columna

Por ejemplo, mostrar solamente los nombres de los productos.

In [ ]:
print(df['producto'])

0              Notebook
1                 Mouse
2             Impresora
3      Silla escritorio
4               Monitor
             ...
145           Audífonos
146            Papel A4
147            Cajonera
148         Memoria RAM
149           Micrófono
Name: producto, Length: 150, dtype: object

## 6. Filtrar productos por precio

Mostrar los productos cuyo precio es mayor que 500.000.

In [ ]:
display(df[df['precio'] > 500000])

,codigo,producto,categoria,ciudad,precio,stock,unidades_vendidas,anio,descuento_porcentaje
0,1001,Notebook,Computación,Concepción,689700,5,73,2024,3.20
32,1033,Notebook,Computación,San Pedro de la Paz,717400,45,31,2025,6.76
64,1065,Notebook,Computación,Concepción,587800,2,102,2025,10.09
96,1097,Notebook,Computación,San Pedro de la Paz,698800,87,29,2025,11.30
128,1129,Notebook,Computación,Concepción,650200,82,150,2024,5.13

## 7. Calcular un promedio

Calcularemos el precio promedio (con dos decimales) de todos los registros.

In [ ]:
print('Precio promedio:', round(df['precio'].mean(), 2))

Precio promedio: 120827.33

## 8. Ejemplos estadísticos con NumPy

Calculamos el precio máximo y el mínimo.

In [ ]:
import numpy as np

precioMax = df['precio'].max()
print('Precio máximo:', precioMax)
precioMin = df['precio'].min()
print('Precio mínimo:', precioMin)

Precio máximo: 717400
Precio mínimo: 4700

## 9. Resumen de datos

Agruparemos por la categoría

In [ ]:
# Agrupar por categoría y calcular el promedio de stock
df_agrupado = df.groupby('categoria')['stock'].mean().round(0)
display(df_agrupado)
df_agrupado = df_agrupado.astype(int)
display(df_agrupado)

categoria
Accesorios     54.0
Computación    43.0
Muebles        42.0
Oficina        54.0
Name: stock, dtype: float64

categoria
Accesorios     54
Computación    43
Muebles        42
Oficina        54
Name: stock, dtype: int64

## 10. Tarea para estudiantes

1. Muestra los últimos 5 registros con `tail()`.
2. Filtra los productos con `stock` menor que 10.
3. Calcula el precio mínimo con Pandas.
4. Agrupar por ciudad y mostrar el menor precio.

In [ ]:
#1.

In [ ]:
#2.

In [ ]:
#3.

In [ ]:
#4.